name: Deploy

on:
    push:
        branches:
            - main

jobs:
    call_deployment_log_workflow_deploying:        
        uses: cw-b/Deployments/.github/workflows/deployment_log.yml@main
        with:
            DEPLOYMENT_STATE: "DEPLOY_STARTED"
            DEPLOYMENT_TOOL: "TEST"
            DEPLOYMENT_ENVIRONMENT: "DEVELOPMENT"
            TENANT: "A0T"
        secrets: inherit
            
    call_deployment_log_workflow_deployed:
        uses: cw-b/Deployments/.github/workflows/deployment_log.yml@main
        needs: call_deployment_log_workflow_deploying
        with:
            DEPLOYMENT_STATE: "DEPLOY_COMPLETED"
            DEPLOYMENT_TOOL: "TEST"
            DEPLOYMENT_ENVIRONMENT: "DEVELOPMENT"
            TENANT: "A0T"
        secrets: inherit
